### ISSUE TITLE
New editor not updating correctly

### ISSUE THREAD

**Issue by SamuraiJack365** [Clooos/Bubble-Card#475]
**Describe the bug**
New UI for editing throws error and doesn't update correctly upon selection. i.e. When I select the tap action on a sub button and then select call service it does not update to display the correct boxes. At the same time when I select the tap action on the main button icon it does the same. 

Further when selecting the tap action for the primary button the auto-fill for the service doesn't function or update the editor as expected.

If I update it with the YAML configuration the visual editor updates correctly, however nothing can be changed via the visual editor. I would expect it would have to do with the way each dialog box is nesting inside the other and there is an error when selecting the correct box to update.

**To Reproduce**
1. Create new button. Mine was a switch type.
2. Set entity to a input_button.helper.
3. Change primary button "Tap action on icon" to "Call service"
4. Attempt to set service.
5. Add sub-button
6. Attempt to change tap action to "Call service"

**Expected behavior**
When I select "Call Service" the form updates for adding a service call.

**Informations (please complete the following information):**

- Browser: Vivaldi 6.6.3271.61 (Stable channel) (64-bit)
  - Revision: 44e5da5a9aa5c707f3a6a779710221ccebcac676
  - JavaScript: V8 12.2.281.28
  - User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
- OS: Windows 11 Version 23H2 (Build 22631.3447)
- Bubble Card version v2.0.0-beta.2
- Home Assistant version:
  - Core 2024.4.3
  - Supervisor 2024.04.0
  - Operating System 12.2
  - Frontend 20240404.2
<details>

<summary>Console log:</summary>

```
bubble-card.js?hacstag=6801129192002:930 Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at k._valueChanged (bubble-card.js?hacstag=6801129192002:930:350)
    at j.handleEvent (lit-html.ts:2018:29)
    at r (fire_event.ts:76:8)
    at i.value (ha-combo-box.ts:321:7)
    at j.handleEvent (lit-html.ts:2018:29)
    at x (property-effects.js:328:43)
    at Object.L [as fn] (property-effects.js:353:3)
    at E (property-effects.js:176:12)
    at property-effects.js:263:18
    at Ue._propertiesChanged (property-effects.js:1925:9)
_valueChanged @ bubble-card.js?hacstag=6801129192002:930
handleEvent @ lit-html.ts:2018
r @ fire_event.ts:76
value @ ha-combo-box.ts:321
handleEvent @ lit-html.ts:2018
x @ property-effects.js:328
L @ property-effects.js:353
E @ property-effects.js:176
(anonymous) @ property-effects.js:263
_propertiesChanged @ property-effects.js:1925
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
_selectedItemChanged @ vaadin-combo-box-mixin.js:1059
$ @ property-effects.js:1038
v @ property-effects.js:140
_propertiesChanged @ property-effects.js:1922
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
_commitValue @ vaadin-combo-box-mixin.js:906
_onClosed @ vaadin-combo-box-mixin.js:897
_openedChanged @ vaadin-combo-box-mixin.js:556
N @ property-effects.js:231
v @ property-effects.js:140
_propertiesChanged @ property-effects.js:1922
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
close @ vaadin-combo-box-mixin.js:394
_overlaySelectedItemChanged @ vaadin-combo-box-mixin.js:1262
__onItemClick @ vaadin-combo-box-scroller-mixin.js:307
Show 30 more frames
Show less
bubble-card.js?hacstag=6801129192002:930 Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at k._valueChanged (bubble-card.js?hacstag=6801129192002:930:350)
    at j.handleEvent (lit-html.ts:2018:29)
    at r (fire_event.ts:76:8)
    at i.value (ha-combo-box.ts:321:7)
    at j.handleEvent (lit-html.ts:2018:29)
    at x (property-effects.js:328:43)
    at Object.L [as fn] (property-effects.js:353:3)
    at E (property-effects.js:176:12)
    at property-effects.js:263:18
    at Ue._propertiesChanged (property-effects.js:1925:9)
_valueChanged @ bubble-card.js?hacstag=6801129192002:930
handleEvent @ lit-html.ts:2018
r @ fire_event.ts:76
value @ ha-combo-box.ts:321
handleEvent @ lit-html.ts:2018
x @ property-effects.js:328
L @ property-effects.js:353
E @ property-effects.js:176
(anonymous) @ property-effects.js:263
_propertiesChanged @ property-effects.js:1925
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
_selectedItemChanged @ vaadin-combo-box-mixin.js:1059
$ @ property-effects.js:1038
v @ property-effects.js:140
_propertiesChanged @ property-effects.js:1922
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
_commitValue @ vaadin-combo-box-mixin.js:906
_onClosed @ vaadin-combo-box-mixin.js:897
_openedChanged @ vaadin-combo-box-mixin.js:556
N @ property-effects.js:231
v @ property-effects.js:140
_propertiesChanged @ property-effects.js:1922
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
close @ vaadin-combo-box-mixin.js:394
_overlaySelectedItemChanged @ vaadin-combo-box-mixin.js:1262
__onItemClick @ vaadin-combo-box-scroller-mixin.js:307
Show 30 more frames
Show less
bubble-card.js?hacstag=6801129192002:930 Uncaught TypeError: Cannot add property target, object is not extensible
    at k._valueChanged (bubble-card.js?hacstag=6801129192002:930:350)
    at j.handleEvent (lit-html.ts:2018:29)
    at r (fire_event.ts:76:8)
    at i.value (ha-combo-box.ts:321:7)
    at j.handleEvent (lit-html.ts:2018:29)
    at x (property-effects.js:328:43)
    at Object.L [as fn] (property-effects.js:353:3)
    at E (property-effects.js:176:12)
    at property-effects.js:263:18
    at Ue._propertiesChanged (property-effects.js:1925:9)
_valueChanged @ bubble-card.js?hacstag=6801129192002:930
handleEvent @ lit-html.ts:2018
r @ fire_event.ts:76
value @ ha-combo-box.ts:321
handleEvent @ lit-html.ts:2018
x @ property-effects.js:328
L @ property-effects.js:353
E @ property-effects.js:176
(anonymous) @ property-effects.js:263
_propertiesChanged @ property-effects.js:1925
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
ready @ property-effects.js:1873
ready @ element-mixin.js:699
ready @ keyboard-mixin.js:20
ready @ focus-mixin.js:43
ready @ vaadin-combo-box-mixin.js:330
ready @ vaadin-combo-box-data-provider-mixin.js:83
ready @ vaadin-combo-box-light.js:169
_enableProperties @ properties-changed.js:362
connectedCallback @ properties-mixin.js:222
connectedCallback @ element-mixin.js:685
connectedCallback @ controller-mixin.js:37
t.connectedCallback @ scoped-custom-element-registry.js:248
k @ lit-html.ts:1411
$ @ lit-html.ts:1454
g @ lit-html.ts:1563
_$AI @ lit-html.ts:1384
z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
_ @ reactive-element.ts:931
k @ lit-element.ts:115
i @ ha-combo-box.ts:63
E @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
setConfig @ bubble-card.js?hacstag=6801129192002:1
value @ hui-element-editor.ts:377
value @ hui-element-editor.ts:128
value @ hui-element-editor.ts:122
value @ hui-element-editor.ts:302
(anonymous) @ hui-element-editor.ts:366
o @ bubble-card.js?hacstag=6801129192002:1
_valueChanged @ bubble-card.js?hacstag=6801129192002:930
handleEvent @ lit-html.ts:2018
r @ fire_event.ts:76
value @ ha-combo-box.ts:321
handleEvent @ lit-html.ts:2018
x @ property-effects.js:328
L @ property-effects.js:353
E @ property-effects.js:176
(anonymous) @ property-effects.js:263
_propertiesChanged @ property-effects.js:1925
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
_selectedItemChanged @ vaadin-combo-box-mixin.js:1059
$ @ property-effects.js:1038
v @ property-effects.js:140
_propertiesChanged @ property-effects.js:1922
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
_commitValue @ vaadin-combo-box-mixin.js:906
_onClosed @ vaadin-combo-box-mixin.js:897
_openedChanged @ vaadin-combo-box-mixin.js:556
N @ property-effects.js:231
v @ property-effects.js:140
_propertiesChanged @ property-effects.js:1922
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
close @ vaadin-combo-box-mixin.js:394
_overlaySelectedItemChanged @ vaadin-combo-box-mixin.js:1262
__onItemClick @ vaadin-combo-box-scroller-mixin.js:307
Show 48 more frames
Show less
bubble-card.js?hacstag=6801129192002:930 Uncaught TypeError: Cannot add property service, object is not extensible
    at k._valueChanged (bubble-card.js?hacstag=6801129192002:930:406)
    at j.handleEvent (lit-html.ts:2018:29)
_valueChanged @ bubble-card.js?hacstag=6801129192002:930
handleEvent @ lit-html.ts:2018
bubble-card.js?hacstag=6801129192002:930 Uncaught TypeError: Cannot add property service, object is not extensible
    at k._valueChanged (bubble-card.js?hacstag=6801129192002:930:406)
    at j.handleEvent (lit-html.ts:2018:29)
_valueChanged @ bubble-card.js?hacstag=6801129192002:930
handleEvent @ lit-html.ts:2018
bubble-card.js?hacstag=6801129192002:930 Uncaught TypeError: Cannot add property service, object is not extensible
    at k._valueChanged (bubble-card.js?hacstag=6801129192002:930:406)
    at j.handleEvent (lit-html.ts:2018:29)
_valueChanged @ bubble-card.js?hacstag=6801129192002:930
handleEvent @ lit-html.ts:2018
bubble-card.js?hacstag=6801129192002:930 Uncaught TypeError: Cannot add property service, object is not extensible
    at k._valueChanged (bubble-card.js?hacstag=6801129192002:930:406)
    at j.handleEvent (lit-html.ts:2018:29)
_valueChanged @ bubble-card.js?hacstag=6801129192002:930
handleEvent @ lit-html.ts:2018
bubble-card.js?hacstag=6801129192002:930 Uncaught TypeError: Cannot add property service, object is not extensible
    at k._valueChanged (bubble-card.js?hacstag=6801129192002:930:406)
    at j.handleEvent (lit-html.ts:2018:29)
_valueChanged @ bubble-card.js?hacstag=6801129192002:930
handleEvent @ lit-html.ts:2018
bubble-card.js?hacstag=6801129192002:930 Uncaught TypeError: Cannot add property service, object is not extensible
    at k._valueChanged (bubble-card.js?hacstag=6801129192002:930:406)
    at j.handleEvent (lit-html.ts:2018:29)
_valueChanged @ bubble-card.js?hacstag=6801129192002:930
handleEvent @ lit-html.ts:2018
bubble-card.js?hacstag=6801129192002:930 Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at k._valueChanged (bubble-card.js?hacstag=6801129192002:930:350)
    at j.handleEvent (lit-html.ts:2018:29)
    at r (fire_event.ts:76:8)
    at i.value (ha-combo-box.ts:321:7)
    at j.handleEvent (lit-html.ts:2018:29)
    at x (property-effects.js:328:43)
    at Object.L [as fn] (property-effects.js:353:3)
    at E (property-effects.js:176:12)
    at property-effects.js:263:18
    at Ue._propertiesChanged (property-effects.js:1925:9)
_valueChanged @ bubble-card.js?hacstag=6801129192002:930
handleEvent @ lit-html.ts:2018
r @ fire_event.ts:76
value @ ha-combo-box.ts:321
handleEvent @ lit-html.ts:2018
x @ property-effects.js:328
L @ property-effects.js:353
E @ property-effects.js:176
(anonymous) @ property-effects.js:263
_propertiesChanged @ property-effects.js:1925
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
_selectedItemChanged @ vaadin-combo-box-mixin.js:1059
$ @ property-effects.js:1038
v @ property-effects.js:140
_propertiesChanged @ property-effects.js:1922
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
_commitValue @ vaadin-combo-box-mixin.js:906
_onClosed @ vaadin-combo-box-mixin.js:897
_openedChanged @ vaadin-combo-box-mixin.js:556
N @ property-effects.js:231
v @ property-effects.js:140
_propertiesChanged @ property-effects.js:1922
_propertiesChanged @ vaadin-combo-box-mixin.js:409
_flushProperties @ properties-changed.js:384
_invalidateProperties @ property-effects.js:1748
Object.defineProperty.set @ properties-changed.js:170
close @ vaadin-combo-box-mixin.js:394
_overlaySelectedItemChanged @ vaadin-combo-box-mixin.js:1262
__onItemClick @ vaadin-combo-box-scroller-mixin.js:307
Show 30 more frames
Show less
```

</details>

**Comment by Clooos** [comment]
Hi and thank you for the feedback! This issue is fixed on my side, I will release a new beta on HACS tomorrow!

**Comment by Clooos** [comment]
This is now working as expected in the new beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3
